name: flet_localisation
description: Flet FletLocalisation control
repository: https://github.com/MyGithubAccount/flet-localisation/src/flutter/flet_localisation
version: 0.5.0
homepage: https://github.com/MyGithubAccount/flet-localisation

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flet: 0.26.0
  flutter:
    sdk: flutter
  mylocalization: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
